// Downloads company favicons for the market map into public/logos/<domain>.png
// and regenerates app/market-map/logos.generated.ts from the directory listing.
//
// Run manually: npm run logos  (add --force to re-fetch existing files)
// Never wire this into prebuild — network in Vercel builds means flaky deploys.

import { createHash } from "crypto";
import { existsSync, mkdirSync, readdirSync, writeFileSync } from "fs";
import { join } from "path";
import { CATEGORIES, MOMENTUM, STACK_COMPANIES, POSITIONING, FINANCIALS, FLOW } from "../app/market-map/data";

const ROOT = join(new URL(".", import.meta.url).pathname, "..");
const LOGO_DIR = join(ROOT, "public", "logos");
const MANIFEST = join(ROOT, "app", "market-map", "logos.generated.ts");
const FORCE = process.argv.includes("--force");
const SIZE = 64;

function collectDomains(): string[] {
  const domains = new Set<string>();
  for (const cat of CATEGORIES) for (const c of cat.companies) if (c.domain) domains.add(c.domain);
  for (const m of MOMENTUM) if (m.domain) domains.add(m.domain);
  for (const s of STACK_COMPANIES) if (s.domain) domains.add(s.domain);
  for (const p of POSITIONING) if (p.domain) domains.add(p.domain);
  for (const f of FINANCIALS) if (f.domain) domains.add(f.domain);
  for (const n of [...FLOW.models, ...FLOW.aggregators, ...FLOW.outputs]) if (n.domain) domains.add(n.domain);
  return [...domains].sort();
}

function faviconUrl(domain: string): string {
  return `https://www.google.com/s2/favicons?domain=${encodeURIComponent(domain)}&sz=${SIZE}`;
}

async function fetchBytes(url: string): Promise<Buffer | null> {
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(15000) });
    if (!res.ok) return null;
    return Buffer.from(await res.arrayBuffer());
  } catch {
    return null;
  }
}

function sha256(buf: Buffer): string {
  return createHash("sha256").update(buf).digest("hex");
}

async function main() {
  mkdirSync(LOGO_DIR, { recursive: true });
  const domains = collectDomains();
  console.log(`${domains.length} unique domains`);

  // The s2 endpoint returns HTTP 200 with a generic globe for unknown domains,
  // so we hash the known-default and reject any body that matches it.
  const globe = await fetchBytes(faviconUrl("thisdomaindoesnotexist-zz123.example"));
  const globeHash = globe ? sha256(globe) : null;

  const misses: string[] = [];
  let fetched = 0, skipped = 0;

  const queue = [...domains];
  async function worker() {
    while (queue.length > 0) {
      const domain = queue.shift()!;
      const out = join(LOGO_DIR, `${domain}.png`);
      if (!FORCE && existsSync(out)) { skipped++; continue; }
      const body = await fetchBytes(faviconUrl(domain));
      if (!body || body.length < 150 || (globeHash && sha256(body) === globeHash)) {
        misses.push(domain);
      } else {
        writeFileSync(out, body);
        fetched++;
      }
      await new Promise((r) => setTimeout(r, 100));
    }
  }
  await Promise.all(Array.from({ length: 4 }, worker));

  // Manifest from the directory listing — files on disk are the source of truth,
  // so hand-sourced PNGs dropped into public/logos/ get picked up on rerun.
  const onDisk = readdirSync(LOGO_DIR)
    .filter((f) => f.endsWith(".png"))
    .map((f) => f.replace(/\.png$/, ""))
    .sort();
  const manifest = [
    "// AUTO-GENERATED by scripts/fetch-logos.ts — do not edit.",
    "export const LOGO_DOMAINS: ReadonlySet<string> = new Set([",
    ...onDisk.map((d) => `  '${d}',`),
    "])",
    "",
  ].join("\n");
  writeFileSync(MANIFEST, manifest);

  console.log(`fetched ${fetched}, skipped ${skipped} existing, manifest lists ${onDisk.length}`);
  if (misses.length > 0) {
    console.log(`\nNo real favicon found for ${misses.length} domain(s) — these fall back to monograms:`);
    for (const d of misses) console.log(`  - ${d}`);
    console.log("Hand-source a PNG into public/logos/<domain>.png and rerun to pick it up.");
  }
}

main();
